name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  my-job-1:
    name: my-job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  my-job-2:
    name: my-job-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
